export const TYPE_LOGIN = {
  ON_GOOGLE_LOGIN_CONFIGURATION: 'ON_GOOGLE_LOGIN_CONFIGURATION',
  ON_GOOGLE_LOGIN_PRESS: 'ON_GOOGLE_LOGIN_PRESS',
  CHANGE_LOGIN_STATE: 'CHANGE_LOGIN_STATE',
  SET_LOGGED_IN_USER_ID: 'SET_LOGGED_IN_USER_ID',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
};
