export const TYPE_CALORIE_TRACKER = {
  APP_INITIALIZED: 'APP_INITIALIZED',
  APP_INITIALIZED_COMPLETED: 'APP_INITIALIZED_COMPLETED',
  ADD_NEW_FOOD_ITEM: 'ADD_NEW_FOOD_ITEM',
  FIND_CALORIE_BURNOUT: 'FIND_CALORIE_BURNOUT',
  UPDATE_CALORIE_BURNOUT_VALUE: 'UPDATE_CALORIE_BURNOUT_VALUE',
  GET_CALORIE_BURNOUT_FROM_FIRESTORE: 'GET_CALORIE_BURNOUT_FROM_FIRESTORE',
};
